### ISSUE TITLE
Maximum call stack size exceeded in PhantomJS

### ISSUE THREAD

**Issue by wilsonjackson** [tubalmartin/karma-chai-sinon#7]
I've submitted a PR to karma-chai here: xdissent#13 but there hasn't been activity on that repo in a long time, and a couple other PRs have been sitting around for >6 months.

I wonder if you might be willing to fold that change into your repo? It's a simple tweak to `adapter.js`.

**Comment by tubalmartin** [comment]
Thanks, will do!

**Comment by wilsonjackson** [comment]
That was quick! Thanks a bunch.
